//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZebraBellaComponentsUtility.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class ComponentRelativePathSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ComponentRelativePathSettings defaultInstance = ((ComponentRelativePathSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ComponentRelativePathSettings())));
        
        public static ComponentRelativePathSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bella")]
        public string ExecutableDirectory {
            get {
                return ((string)(this["ExecutableDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("belladomain.exe")]
        public string ExecutableFile {
            get {
                return ((string)(this["ExecutableFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bella/storage")]
        public string StorageDirectory {
            get {
                return ((string)(this["StorageDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bella/logs")]
        public string LogsDirectory {
            get {
                return ((string)(this["LogsDirectory"]));
            }
        }
    }
}
