//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZebraBellaComponentsUtility.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class MiscellaneousSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MiscellaneousSettings defaultInstance = ((MiscellaneousSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MiscellaneousSettings())));
        
        public static MiscellaneousSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int BellaCloseDelay {
            get {
                return ((int)(this["BellaCloseDelay"]));
            }
        }
    }
}
